 
# language: python
language: java

sudo: true

os: linux

addons:
    apt:
      packages:
            - oracle-java9-installer

jdk:
  - oraclejdk8

services:
    - docker
    - redis-server

# sudo: true

# group: deprecated-2017Q4

# dist: trusty

# os: linux

python:
   - "2.7"

branches:
  only:
   - master

install:
   - sudo pip install pytest
   - sudo pip install pytest-html

script: 
  - ./travis_build.sh

notifications:
  email:
     recipients:
      - testeda@163.com
     on_success: always
     on_failure: always
