 
language: python

# sudo: true

# group: deprecated-2017Q4

# dist: trusty

# os: linux

python:
   - "3.6"

branches:
  only:
   - master

install:
   - pip install pytest-html

script: 
  - pytest
  - travis_build.sh

notifications:
  email:
     recipients:
      - testeda@163.com
     on_success: always
     on_failure: always
